language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:

    # submit coverage report
    - if [[ "$MATLAB_VER" == "R2017b" && "$ARCH" == "Linux" ]]; then
      bash <(curl -s https://codecov.io/bash) -f "!*.lst";
      fi

    # deploy documentation GIT_BRANCH=$GIT_BRANCH
    - if [[ "$MATLAB_VER" == "R2017b" && "$ARCH" == "Linux" && "$JENKINS_PULL_REQUEST" != "True" ]]; then
      export PATH="/home/sbg-jenkins/.local/bin":$PATH;
      pip install --upgrade --user -r docs/requirements.txt;
      python ~/github_stats.py $(pwd)/docs/source/list_contributors.rst;
      ssh -t sbg-jenkins@10.184.148.14 'env >> ~/env1.txt && cd ~/tmp/cobratoolboxForTutorials && git checkout develop && git pull origin develop && git submodule update --init && $(pwd)/docs/prepareTutorials.sh -c=$(pwd) -t=~/tmp/COBRA.tutorials -p=~/tmp -m=html,pdf,png && env >> ~/env2.txt';
      fi
