language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:
    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:

    # submit coverage report
    - if [[ "$MATLAB_VER" == "R2017b" && "$ARCH" == "Linux" ]]; then
      bash <(curl -s https://codecov.io/bash) -f "!*.lst";
      fi

    # deploy documentation
    - if [[ "$MATLAB_VER" == "R2017b" && "$ARCH" == "Linux" && "$JENKINS_PULL_REQUEST" != "True" ]]; then
      export PATH="/home/jenkins/.local/bin":$PATH;
      pip install --upgrade --user -r docs/requirements.txt;
      python ~/github_stats.py $(pwd)/docs/source/list_contributors.rst;
      export GIT_LOCAL_BRANCH=${GIT_BRANCH##origin/};
      echo $GIT_LOCAL_BRANCH;
      cd $ARTENOLIS_DATA_PATH/repos/COBRA.tutorials && git stash && git checkout $GIT_LOCAL_BRANCH && git pull origin $GIT_LOCAL_BRANCH;
      cd $ARTENOLIS_DATA_PATH/repos/cobratoolbox && git stash && git checkout $GIT_LOCAL_BRANCH && git pull origin $GIT_LOCAL_BRANCH && git submodule update --init;
      python -c "from documenter.deploy import Documentation; doc = Documentation('github.com/opencobra/cobratoolbox', local_upstream='$(pwd)', ci='jenkins'); doc.deploy()";
      bash .artenolis/generateZip.sh;
      fi
