language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - git submodule update --force --init --recursive

script:
    - CURRENT_DIR=`pwd`
#    - if [ "$MATLAB_VER" == "R2016b" ]; then
    - cd ./test/models
    - sh ./retrieveModels.sh
    - cd $CURRENT_DIR #fi
    - sh ./runtests.sh

#deploy:

after_success:
    - if [ "$MATLAB_VER" == "R2016b" ]; then bash <(curl -s https://codecov.io/bash); fi
